### ISSUE TITLE
[Feature Proposal] Extensible Library API

### ISSUE THREAD

**Issue by pbone64** [rejuvena/tea-framework#5]
### Description

An extensible library API would provide a centralized system to allow mods to override and/or modify the behaviour of Tea Framework features and features of library mods created for Tea Framework. This would be done by adding a collection of objects containing the library's logic to `ITeaMod`.

### What does this proposal attempt to solve or improve?

While it is currently possible to achieve this, it is difficult to do it cleanly and nigh impossible to do consistently across Tea and library mods.

### What (other) solutions may be considered?

This could be ignored in favour of letting Tea and libraries either:
- Do whatever they want.
- Making a standard and hoping libraries follow it.

I believe that my proposed solution is ideal, however, because it ensures consistency across mods.

**Comment by steviegt6** [comment]
Done in a6e6fe928e92ec1790a2f63d216d01912f86adc5 and cc0612c3885615091be421343771f13d96ee42b9.
