### ISSUE TITLE
[Feature Proposal] Split up Tea

### ISSUE THREAD

**Issue by pbone64** [rejuvena/tea-framework#6]
### Description

I propose separating (what is currently known as) Tea Framework into two pieces:
* Tea Core: An abstraction layer over tModLoader.
* Tea Framework: A library mod for Tea Core that provides many useful features.

### What does this proposal attempt to solve or improve?

It creates a separation of interests between abstraction and library/utils, and it allows us to update one without needing to update the other.

### What (other) solutions may be considered?

N/A.

**Comment by steviegt6** [comment]
*This may be re-opened at a later date after further discussion.*
Closing this issue for now, we have mostly settled on keeping Tea Framework itself small, with only features (for the most part). Secondary libraries will be developed for specific, non-essential features.
